export const testimonials = [
    {
        "name":"Jane",
        "org":"The Triangle",
        "img":"/src/assets/trojan.png",
        "quote":"\"The Mecca has done so much for my organization.\"",
        "link":"https://bit.ly/elonpark",
        'number': 0,
    },
    {
        "name":"Jane",
        "org":"The Triangle",
        "img":"/src/assets/trojan.png",
        "quote":"\"The Mecca has done so much for my organization.\"",
        "link":"https://bit.ly/elonpark",
        'number': 1,
    },
    {
        "name":"Jane",
        "org":"The Triangle",
        "img":"/src/assets/trojan.png",
        "quote":"\"The Mecca has done so much for my organization.\"",
        "link":"https://bit.ly/elonpark",
        'number': 2,
    },
    {
        "name":"Jane",
        "org":"The Triangle",
        "img":"/src/assets/trojan.png",
        "quote":"\"The Mecca has done so much for my organization.\"",
        "link":"https://bit.ly/elonpark",
        'number': 3,
    },
    {
        "name":"Jane",
        "org":"The Triangle",
        "img":"/src/assets/trojan.png",
        "quote":"\"The Mecca has done so much for my organization.\"",
        "link":"https://bit.ly/elonpark",
        'number': 4,
    },
    {
        "name":"Jane",
        "org":"The Triangle",
        "img":"/src/assets/trojan.png",
        "quote":"\"The Mecca has done so much for my organization.\"",
        "link":"https://bit.ly/elonpark",
        'number': 5,
    },
]