export const testimonials = [
    {
        "name":"Joyce Smyrna",
        "org":"Triangle Volunteer Center",
        "img":"/src/assets/stockportraits/oldwhitewomanstockimage (1).jpg",
        "quote":"\"Hosting at the Marvin Ridge Mecca was a breeze!.\"",
        "link":"none",
        'number': 0,
    },
    {
        "name":"Chris Yamagata",
        "org":"Nothing But Noodles",
        "img":"/src/assets/stockportraits/oldasianmanstockimage.jpg",
        "quote":"\"Our annual Night Noodle campaign, held at the Mecca, was a huge success.\"",
        "link":"none",
        'number': 1,
    },
    {
        "name":"Ryan Vazquez",
        "org":"La Victoria",
        "img":"/src/assets/stockportraits/brazillianstockphoto.png",
        "quote":"\"I can't tell you enough about the Mecca's stellar amenities.\"",
        "link":"none",
        'number': 2,
    },
    {
        "name":"Yin Li",
        "org":"Li's Chocolate Emporium",
        "img":"/src/assets/stockportraits/chinesewomanstockimage.jpg",
        "quote":"\"The Mecca staff helped me sell my chocolate safely & securely.\"",
        "link":"none",
        'number': 3,
    },
    {
        "name":"James Evenstock",
        "org":"RokBar",
        "img":"/src/assets/stockportraits/whitemanstockportrait.jpg",
        "quote":"\"A state boxing championship? In a gym? It's possible at the Mecca.\"",
        "link":"none",
        'number': 4,
    },
    {
        "name":"Elise O'Grady",
        "org":"No Child Left Behind",
        "img":"/src/assets/stockportraits/youngwhitewomanstockimage_realistic.jpg",
        "quote":"\"The Mecca's top-of-the-line food service made our kids so happy!\"",
        "link":"none",
        'number': 5,
    },
]